import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Box,Layers,ScanLine,Check,ArrowRight,ChevronRight,Upload,RotateCcw,SlidersHorizontal,FileText,Palette,Activity,Download,X,LoaderCircle,Plus,CheckCircle2,AlertCircle}from'lucide-react';
import './style.css';
type Rule={rule_id:string;category:string;title:string;target:string;source:string;confidence_type:string};
type Profile={brand:string;version:number;principles:string[];rules:Rule[]};
type Finding={finding_id:string;rule_id:string;category:string;title:string;status:string;object_id:string;observation:string;expectation:string;source:string;confidence_type:string;evidence_type:string;reasoning:string;change:any;scene_version:string;dismissal_reason?:string};
type State={name:string;brief:string;profile:Profile;profile_approved:boolean;plan:{width_mm:number;height_mm:number;rationale:string};plan_approved:boolean;current:string|null;versions:{id:string;kind:string}[];findings:Finding[];status:string;error:string|null;job:any;capabilities:{ai:boolean;blender:boolean;blender_mcp:boolean};manifest:any;uploads:any[]};
const views=['three_quarter','front','detail']; const viewNames=['Three-quarter','Front','Detail'];
async function api(path:string,body?:any){const r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'Please check the supplied values.');return d;}
function App(){
const[s,setS]=useState<State|null>(null),[tab,setTab]=useState('Review'),[view,setView]=useState(0),[selected,setSelected]=useState(''),[filter,setFilter]=useState('All'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<any>(null),[profile,setProfile]=useState<Profile|null>(null),[plan,setPlan]=useState<State['plan']|null>(null),[source,setSource]=useState(''),[compare,setCompare]=useState(false),[reason,setReason]=useState(''),[brief,setBrief]=useState<string|null>(null);
const refresh=async()=>{const d=await api('state');setS(d);return d};
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();for(const tool of [{name:'read_design_review',description:'Read current scene and brand findings; does not approve changes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{const d=await refresh();return{scene:d.current,status:d.status,findings:d.findings}}},{name:'run_brand_rule_review',description:'Run measured rule checks on the current scene. Never applies revisions or approvals.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async()=>{await api('review',{});const d=await refresh();return{status:d.status,findings:d.findings}}}])Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
useEffect(()=>{refresh().catch(e=>setError(e.message));const t=setInterval(()=>refresh().catch(()=>{}),2500);return()=>clearInterval(t)},[]);
async function action(path:string,body:any={},after?:()=>void){setBusy(true);setError('');try{const d=await api(path,body);await refresh();after?.();return d}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
if(!s)return <div className="loading"><LoaderCircle className="spin"/> Connecting to your workspace…{error&&<p>{error}</p>}</div>;
const working=busy||s.job?.status==='running'; const findings=s.findings.filter(f=>filter==='All'||f.status===filter);const f=s.findings.find(f=>f.finding_id===selected)||findings[0];const count=(status:string)=>s.findings.filter(f=>f.status===status).length;
const p=profile||s.profile; const pl=plan||s.plan;const image=(version:string|null,v=view)=>version?`/artifacts/${version}/${views[v]}.png`:'';
return <div className="app"><aside className="rail"><a className="logo" href="#" aria-label="Vela home">v.</a><button aria-label="Review workspace" className={tab==='Review'?'active':''} onClick={()=>setTab('Review')}><Box/></button><button aria-label="Brand profile" className={tab==='Brand profile'?'active':''} onClick={()=>setTab('Brand profile')}><Palette/></button><button aria-label="Generation plan" className={tab==='Build plan'?'active':''} onClick={()=>setTab('Build plan')}><Layers/></button><span className="rail-bottom">V</span></aside>
<div className="shell"><header><div className="breadcrumb">Workspace <ChevronRight size={14}/><strong>Vela desktop speaker</strong><span className="project-tag">CONCEPT 01</span></div><div className="header-right"><span className="connection">{s.capabilities.blender_mcp?'Blender MCP connected':'Blender MCP offline'}</span><span className="connection">{s.capabilities.ai?'AI connected':'Prepared demo rules'}</span><button className="icon-button" aria-label="Reset demo project" title="Reset demo workflow; existing files are preserved" disabled={working} onClick={()=>action('demo',{},()=>{setProfile(null);setPlan(null);setTab('Brand profile')})}><RotateCcw size={17}/></button></div></header>
<div className="heading"><div><div className="eyebrow">BRAND-AWARE PRODUCT DESIGN</div><h1>Your brand. In every detail.</h1><p>From design intent to a concept that belongs.</p></div><button className="primary" disabled={working||!s.current||!s.profile_approved} onClick={()=>action('review',{},()=>setTab('Review'))}>{working?<LoaderCircle className="spin" size={17}/>:<ScanLine size={17}/>} Run brand review</button></div>
<nav className="tabs">{['Review','Brand profile','Build plan','Versions'].map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}{t==='Review'&&s.findings.length>0&&<span>{s.findings.length}</span>}</button>)}<span className="save-state">{working?'Working…':s.status==='approved'?'Concept approved':'Saved locally'}</span></nav>
{(error||s.error)&&<div className="error" role="alert"><AlertCircle size={18}/>{error||s.error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
{s.job?.status==='running'&&<div className="progress"><LoaderCircle size={16} className="spin"/>{s.job.stage} · Your previous version stays available.</div>}
{tab==='Review'&&<div className="review-grid"><section className="stage"><div className="stage-toolbar"><span><Box size={16}/> Desktop speaker <small>{s.current?'EDITABLE BLENDER SCENE':'NOT GENERATED'}</small></span><button className={compare?'toggle on':'toggle'} disabled={s.versions.length<2} onClick={()=>setCompare(!compare)}><Layers size={15}/> Compare</button></div>
<div className={'render '+(compare?'comparison':'')}>{s.current?<>{compare&&<figure><img src={image(s.versions[0].id)} alt="Original speaker render"/><figcaption>Original</figcaption></figure>}<figure><img src={image(s.current)} alt={`${viewNames[view]} render of editable Vela speaker`}/>{compare&&<figcaption>Current</figcaption>}</figure><span className="render-label">VELA / 001<br/><small>DESKTOP SMART SPEAKER</small></span></>:<div className="empty"><Box size={48} strokeWidth={1}/><h2>A concept starts with its brand.</h2><p>Review Vela’s design rules, approve the build plan,<br/>then create your editable speaker.</p><button className="primary" onClick={()=>setTab('Brand profile')}>Review brand profile <ArrowRight size={16}/></button></div>}</div>
<div className="view-controls">{viewNames.map((n,i)=><button key={n} className={view===i?'selected':''} onClick={()=>setView(i)}>{n}</button>)}<span>1000 × 1000</span></div>
<div className="object-panel"><div className="section-label">SCENE OBJECTS <span>{s.manifest?.objects.filter((o:any)=>['MESH','FONT'].includes(o.type)).length||0}</span></div><div className="objects">{s.manifest?.objects.filter((o:any)=>['MESH','FONT'].includes(o.type)&&o.object_id!=='studio_ground').map((o:any)=><button key={o.object_id} className={f?.object_id===o.object_id?'selected':''} onClick={()=>{const match=s.findings.find(a=>a.object_id===o.object_id);if(match)setSelected(match.finding_id);void api('selection',{object_id:o.object_id}).catch(e=>setError(e.message))}}><Box size={14}/>{o.object_id.replace(/_01$/,'').replaceAll('_',' ')}</button>)}</div>{s.current&&<a className="download" href={`/artifacts/${s.current}/scene.blend`} download><Download size={14}/> Download editable scene</a>}</div></section>
<aside className="findings"><div className="findings-title"><h2>Brand review</h2><span className="mini-label">{s.findings.length?'MEASURED EVIDENCE':'READY WHEN YOU ARE'}</span></div><div className="stats"><div><strong className="red">{count('FAIL')}</strong><span>Needs attention</span></div><div><strong className="green">{count('PASS')}</strong><span>Passed</span></div><div><strong className="amber">{count('REVIEW')}</strong><span>Human review</span></div></div>
<div className="filter">{['All','FAIL','PASS','REVIEW'].map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x==='All'?'All findings':x==='FAIL'?'Issues':x==='PASS'?'Passed':'Review'}</button>)}</div>
<div className="finding-list">{!s.findings.length&&<p className="quiet">Generate a scene and run a review to see rule-level evidence here.</p>}{findings.map(a=><button key={a.finding_id} className={'finding '+(f?.finding_id===a.finding_id?'selected':'')} onClick={()=>{setSelected(a.finding_id);setReason('');if(a.object_id)void api('selection',{object_id:a.object_id}).catch(e=>setError(e.message))}}><span className={'status-mark '+a.status}>{a.status==='PASS'?<Check size={13}/>:a.status==='FAIL'?'!':'?'}</span><span><small>{a.category} · {a.rule_id}</small><strong>{a.title}</strong><em>{a.dismissal_reason?'Exception recorded':a.object_id||'Scene-level review'}</em></span><ChevronRight size={16}/></button>)}</div>
{f&&<div className="evidence"><div className="section-label">EVIDENCE <span>{f.evidence_type}</span></div><p className="observation">{f.observation}</p><p>{f.reasoning}</p><div className="source"><FileText size={14}/><span>{f.source}<small>{f.confidence_type}</small></span></div>{f.change?<button className="primary full" disabled={working||!s.profile_approved} onClick={async()=>{const d=await action('preview',{finding_id:f.finding_id});if(d)setPreview(d)}}><SlidersHorizontal size={16}/> Preview suggested fix <ArrowRight size={16}/></button>:f.status!=='PASS'&&<><label className="small-label">Intentional exception / review note<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain your design decision"/></label><button disabled={working||!reason.trim()} onClick={()=>action('dismiss',{finding_id:f.finding_id,reason})}>Record exception</button></>}</div>}
<div className="review-footer"><button disabled={working||!s.capabilities.ai||!s.current} onClick={()=>action('visual-review')}><Activity size={15}/> Visual AI review</button><button disabled={working||!s.findings.length} onClick={()=>action('approve-concept')}><CheckCircle2 size={15}/> Approve concept</button></div></aside></div>}
{tab==='Brand profile'&&<div className="configuration"><section className="panel intro-panel"><div className="eyebrow">01 / BRAND CONTEXT</div><h2>Quiet confidence.<br/>Warm precision.</h2><p>Vela is the prepared demo brand. Review each rule before it guides your concept.</p><div className="swatches"><span style={{background:'#c0ad89'}}/><span style={{background:'#34383a'}}/><span style={{background:'#c58b3c'}}/></div><p className="small-label">Warm ceramic · Charcoal textile · Muted amber</p><label>Brand guideline or principles<textarea value={source} onChange={e=>setSource(e.target.value)} placeholder="Paste brand context, or upload a guideline below." rows={6}/></label><label className="upload"><Upload size={18}/> Add guideline, logo or reference<input type="file" accept=".pdf,.md,.txt,.png,.jpg,.jpeg,.webp" onChange={async e=>{if(!e.target.files?.[0])return;const fd=new FormData();fd.append('file',e.target.files[0]);setBusy(true);try{const r=await fetch('/api/upload',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw Error(d.detail);if(d.text)setSource(d.text);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}/></label>{s.uploads.map(u=><p key={u.id} className="small-label"><FileText size={13}/> {u.name}</p>)}<button disabled={working||!s.capabilities.ai} onClick={()=>action('extract-profile',{text:source},()=>setProfile(null))}>Extract rules with AI</button>{!s.capabilities.ai&&<p className="quiet">Live AI needs backend API configuration. You can edit and approve the prepared rules now.</p>}</section><section className="panel rules"><div className="panel-heading"><div><div className="eyebrow">BRAND DESIGN PROFILE</div><h2>Design rules</h2></div><span className="pill">{s.profile_approved?'Approved':'Awaiting approval'}</span></div>{p.rules.map((r,i)=><div className="rule" key={r.rule_id}><div><small>{r.category} / {r.rule_id}</small><h3>{r.title}</h3><p>{r.source} · {r.confidence_type}</p></div><label>Target<input value={r.target} onChange={e=>{const n=structuredClone(p);n.rules[i].target=e.target.value;n.rules[i].confidence_type='Designer-defined';setProfile(n)}}/></label></div>)}<button className="primary" disabled={working} onClick={()=>action('profile',{profile:p,approved:true},()=>{setProfile(null);setTab('Build plan')})}><Check size={17}/> Approve profile & continue</button></section></div>}
{tab==='Build plan'&&<div className="configuration"><section className="panel intro-panel"><div className="eyebrow">02 / PRODUCT PLAN</div><h2>A calm presence.<br/>Built for your desk.</h2><label>Product brief<textarea rows={5} value={brief??s.brief} onChange={e=>setBrief(e.target.value)}/></label><button disabled={working||brief===null} onClick={()=>action('brief',{brief},()=>setBrief(null))}>Save brief</button><div className="part-list">{['Soft ceramic body','Acoustic textile grille','Top controls','Restrained status ring','Subtle Vela branding','Grounded base'].map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div></section><section className="panel"><div className="panel-heading"><h2>Approve the build</h2><span className="pill">{s.plan_approved?'Approved':'Draft plan'}</span></div><div className="dimension-fields"><label>Body width · mm<input type="number" min="120" max="240" value={pl.width_mm} onChange={e=>setPlan({...pl,width_mm:Number(e.target.value)})}/></label><label>Body height · mm<input type="number" min="170" max="330" value={pl.height_mm} onChange={e=>setPlan({...pl,height_mm:Number(e.target.value)})}/></label></div><label>Design rationale<textarea rows={5} value={pl.rationale} onChange={e=>setPlan({...pl,rationale:e.target.value})}/></label><p className="quiet">This bounded builder creates six editable components, warm ceramic and charcoal materials, and three review cameras.</p><div className="button-row"><button disabled={working||!s.profile_approved||!s.capabilities.ai} onClick={()=>action('plan-ai',{},()=>setPlan(null))}>Draft with AI</button><button className="primary" disabled={working||!s.profile_approved} onClick={()=>action('plan',{plan:pl,approved:true},()=>setPlan(null))}><Check size={16}/> Approve plan</button></div><hr/><h3>Create the concept</h3><p>Generation creates a new scene. Existing versions are preserved.</p><button className="primary full" disabled={working||!s.plan_approved||!!plan} onClick={()=>action('generate',{approved:true,seeded:false},()=>setTab('Review'))}><Plus size={17}/> Generate approved concept</button><button className="full" disabled={working||!s.plan_approved||!!plan} onClick={()=>action('generate',{approved:true,seeded:true},()=>setTab('Review'))}>Build diagnostic demo · 6 seeded issues</button><p className="quiet">Diagnostic mode deliberately changes the plan’s dimensions and finishes to demonstrate the review workflow.</p></section></div>}
{tab==='Versions'&&<section className="panel history"><div className="eyebrow">SCENE HISTORY</div><h2>Every decision, preserved.</h2>{!s.versions.length&&<p>No scene versions yet. Approve a plan to begin.</p>}{s.versions.map((v,i)=><div className="version" key={v.id}><img src={image(v.id,0)} alt={`Scene version ${i+1}`}/><div><small>VERSION {String(i+1).padStart(2,'0')}</small><h3>{v.kind}</h3><p>{v.id}</p></div><a href={`/artifacts/${v.id}/scene.blend`} download>Download .blend</a><button disabled={working||v.id===s.current} onClick={()=>action('restore',{version:v.id},()=>setTab('Review'))}>{v.id===s.current?'Current':'Restore'}</button></div>)}</section>}
<footer><span><Layers size={13}/> Vela design workspace</span><span>Editable scenes. Evidence-led decisions.</span><span>LOCAL MVP / 0.1</span></footer></div>
{preview&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="preview-title"><button className="close" aria-label="Close preview" onClick={()=>setPreview(null)}><X/></button><div className="eyebrow">DESIGNER APPROVAL</div><h2 id="preview-title">A precise change.<br/>Your decision.</h2><p>{preview.change.object_id} · {preview.change.property}</p><div className="diff"><div><small>CURRENT</small><strong>{String(preview.change.before)}</strong></div><ArrowRight/><div><small>PROPOSED</small><strong>{String(preview.change.after)}</strong></div></div><p className="quiet">We’ll save a backup, change this property, render three fresh views, and recheck the rules. Other objects stay unchanged.</p><button className="primary full" disabled={working} onClick={async()=>{const d=await action('apply',{preview_id:preview.preview_id,approved:true});if(d){setPreview(null);setCompare(true)}}}>Approve change & verify <ArrowRight size={17}/></button><button className="full" onClick={()=>setPreview(null)}>Keep current design</button></section></div>}
</div>}
createRoot(document.getElementById('root')!).render(<App/>);
